### ISSUE TITLE
How to test my custom video with Amodal-expander

### ISSUE THREAD

**Issue by zweiPA** [WesleyHsieh0806/Amodal-Expander#1]
the demo.py seem is not for Amodal, how to test my custom video, and output the results

**Comment by WesleyHsieh0806** [comment]
We are working on the modification of demo.py and will release it around next week. 

At this point,
you can follow the instructions [here](https://github.com/WesleyHsieh0806/Amodal-Expander/blob/main/datasets/README.md#customized-dataset) to run inference on customized datasets. 

After the inference, you will get a `lvis_instances_results.json`, which can be used for visualization using our [provided scripts](https://github.com/WesleyHsieh0806/TAO-Amodal/tree/main/visualization#1-visualize-predictions-json).

**Comment by zweiPA** [comment]
thank you for you response, I look forward to your update

**Comment by Mohit-robo** [comment]
> We are working on the modification of demo.py and will release it around next week.
> 
> At this point, you can follow the instructions [here](https://github.com/WesleyHsieh0806/Amodal-Expander/blob/main/datasets/README.md#customized-dataset) to run inference on customized datasets.
> 
> After the inference, you will get a `lvis_instances_results.json`, which can be used for visualization using our [provided scripts](https://github.com/WesleyHsieh0806/TAO-Amodal/tree/main/visualization#1-visualize-predictions-json).

Hey any updates on this thing.

**Comment by WesleyHsieh0806** [comment]
Hi @Mohit-robo and @zweiPA 
Thanks for waiting, please check the [demo](https://github.com/WesleyHsieh0806/Amodal-Expander/?tab=readme-ov-file#robot-demo) section. Feel free to [customize the visualizer](https://github.com/WesleyHsieh0806/Amodal-Expander/blob/main/gtr/predictor.py).

**Comment by Mohit-robo** [comment]
> Hi @Mohit-robo and @zweiPA Thanks for waiting, please check the [demo](https://github.com/WesleyHsieh0806/Amodal-Expander/?tab=readme-ov-file#robot-demo) section. Feel free to [customize the visualizer](https://github.com/WesleyHsieh0806/Amodal-Expander/blob/main/gtr/predictor.py).

Great thanks, for that. Will surely try this.
